### ISSUE TITLE
Cleanup: events UI

### ISSUE THREAD

**Issue by lukewendling** [Sotera/watchman#106]
## Tasks

- [ ] show spinner when loading events
- [ ] make the spinner more noticeable
- [ ] remove 'aggevent' references
- [ ] hide map if no points to plot
- [ ] project fields in smposts queries to greatly reduce bits over wire
- [ ] misc code cleanup
