### ISSUE TITLE
Modify QCR filtering to play nicely with multiple web processes

### ISSUE THREAD

**Issue by lukewendling** [Sotera/watchman#135]
## TODO

- [x] use env var, instead of local var, to maintain target-posts-per-second. 
- [x] remove loopback endpoints.
- [x] also add env vars for: dupe checking interval, and num. of days back to ignore old posts. so we can modify in other environs.

@justinlueders @drJAGartner
