### ISSUE TITLE
Create simple websocket server to serve real-time charts

### ISSUE THREAD

**Issue by lukewendling** [Sotera/watchman#143]
## TODO

- [ ] runs in separate server process from api.
- [ ] can broadcast messages or send to single socket-only.
- [ ] modules-as-handlers for extensibility.
- [ ] scales via sl-pm's env-set.
